### ISSUE TITLE
CVS 생성 절차 개선

### ISSUE THREAD

**Issue by hajinhoe** [hajinhoe/ericatrend#3]
진행중
- 크롤러에서 중복이 발생함
- 크롤러에서 누락이 발생함
- 크롤러 생성 CVS 파일의 디아메터와 랩퍼 (진행)
- 뉴에서에서 기계로 탐지하는 것을 막을 적당한 시간 수정
- 뉴에그에 세부정보 (사이즈, CPU) 등이 있는 경우 추가로 수집 (진행)
- MariaDB에서 뷰를 만들어서 일렉서치에서 보기 편하도록 관리

완료
- 가격 정보에서 0을 받는 문제
- 가격 정보에서 새로 객체를 불러 올 때마다 파일을 생성해야 하는 문제
- 가격 정보 CVS 파일의 디아메터와 랩퍼 (, 및 "")

**Comment by hajinhoe** [comment]
뉴에그 시간 설정 시나리오:
페이지마다 0~40 분 랜덤하게 쉬게함.
제품마다 0~2분 랜덤하게 쉬게함.
리뷰마다 0~10초 랜덤하게 쉬게함.

**Comment by qeads2** [comment]
**- 뉴에서에서 기계로 탐지하는 것을 막을 적당한 시간 수정 (진행)**
올려주신 시나리오대로 일단 설정해서 현재 서버에서 크롤링 중입니다.

**- 크롤러에서 중복이 발생함 (진행)**
제품 내에서 페이지를 넘어가는 부분이 문제라고 생각해서, 일단 조건을 손봤는데 당장 확인하기가 어려워서 일단 서버에서 크롤링 진행 중입니다.

그런데, 혹시 처음에 임시로 엑셀에서 중복값 제거하셨다고 했을 때, 어떤 방식으로 제거하셨는지 알 수 있을까요?

**Comment by qeads2** [comment]
뉴에그 시간 설정 시나리오: ( 수정 )

**페이지마다 0~20 분 랜덤하게 쉬게함.**

제품마다 0~2분 랜덤하게 쉬게함.

리뷰마다 0~10초 랜덤하게 쉬게함.
